import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/features/ui/toaster";
import { SignupModal } from "@/features/auth/signup";
import { LoginModal } from "@/features/auth/login";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: "Snapcode | %s",
    default: "Snapcode",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <SignupModal />
        <LoginModal />
        {children}
      </body>
    </html>
  );
}
